### ISSUE TITLE
It crashed when create a custom attribute in the catalog

### ISSUE THREAD

**Issue by kanodoe** [Creare/CreareSEO#15]
Mi site crashes after I add a custom attribute to the products and throws this error:

```
Fatal error: Call to a member function getFrontend() on a non-object in /home/mousecat/public_html/addons/wooopa/app/code/community/Creare/CreareSeoCore/Helper/Meta.php on line 93
```

The only way to get back the web is comment that line but the title in the website is bad:
```
<title>- Wooopa Tu Lugar de Descuentos</title>
```

**Comment by adampmoss** [comment]
Hello, if you disable page title rewrites in the configuration this should fix the issue. In terms of why this error occurs I'm not sure. What type of attribute did you add and what was the shortcode you used for it?

**Comment by kanodoe** [comment]
Actually it works.

The custom attribute was about color and model of the product. But changing the configuration fix the problem.

Thanks
