### ISSUE TITLE
Disabled product redirects produce 'white page'

### ISSUE THREAD

**Issue by gpcola** [Creare/CreareSEO#18]
@adampmoss

Hi,

Thanks - Nice extension which works very well on my store except for one thing;

I seem to have a problem with the url rewrites for disabled products. It doesn't matter whether I opt to redirect to category, home page, product sku or 404 - visiting the product page produces a white page. Same thing happens with disabed categories.

Seems to only be happening when running compiled.  Reported error is:

Array
(
    [type] => 64
    [message] => Cannot redeclare class Mage_Catalog_Block_Breadcrumbs
    [file] => /home/xx/public_html/magento/includes/src/__catalog.php
    [line] => 77
)

I disabled every extension except Creareseo, recompiled, cleared cache but to no avail.

Any ideas where I should start looking for the cause?

CE 1.9.1.1
Creareseo 1.2.2

**Comment by adampmoss** [comment]
Thanks for letting us know. We've had a few reported issues with the compiler and will look into this issue for the next release.

**Comment by adampmoss** [comment]
Hello, we've tried to replicate this issue but have been unable to. Looking at this MageOverflow post it may be to do with the cache: http://magento.stackexchange.com/questions/5678/code-compilation-error-cannot-redeclare-class

I know for a fact that the extension doesn't try to redeclare the breadcrumb block class - it just uses a new template.

**Comment by gpcola** [comment]
@adampmoss ok, thanks for getting back to me.  Your reply confused me tho because I was sure I had tested this so I just now created a brand new Magento instal, added one test product and installed nothing but CreareSEO - I get exactly the same issue as before when disabling that product.  Would you like to take a look at it?

**Comment by adampmoss** [comment]
@gpcola - ah I've managed to replicate it now - missed the bit where you said you had it compiled. I'll see if there's a fix and get back to you.

**Comment by adampmoss** [comment]
Ok, so apparently this is the cause: http://brimllc.com/2012/03/magento-fun-with-debugging-the-magento-compiler/

The 301 redirect script uses the same controller_action_predispatch event to hook into, just gotta figure out a way to prevent the breadcrumbs from being involved when this event occurs.

**Comment by adampmoss** [comment]
Ok, so apparently this is the cause: http://brimllc.com/2012/03/magento-fun-with-debugging-the-magento-compiler/

The 301 redirect script uses a similar event to hook into (just gotta figure out a way to prevent the breadcrumbs from being involved when this event occurs.

**Comment by adampmoss** [comment]
On further investigation, this error seems to be a core issue. If you take a vanilla install of Magento and disable a product with compilation switched on we have the same error.

**Comment by gpcola** [comment]
Damn, you're right it does :/  I apologise for not thinking to test that myself...

Maybe related to this EE bug http://magento.stackexchange.com/questions/49769/internal-server-error-when-viewing-disabled-product-enterprise?

So sorry for wasting your time :(

**Comment by adampmoss** [comment]
No problem man. This is why I never use compilation!
