### ISSUE TITLE
existing robots.txt cannot be found

### ISSUE THREAD

**Issue by hans2103** [Creare/CreareSEO#22]
on my multi domain Magento site I have put robots.txt into a subdirectory. This way I can provide a domain specific robots.txt. (domain.com/robots/domain.com/robots.txt and example.com/robots/example.com/robots.txt)

using .htaccess to indicate the correct position of robots.txt

    # Rewrite URL for robots.txt
    RewriteRule ^robots\.txt$ robots/%{HTTP_HOST}/robots.txt [L]

But... since I have an alternate position of my robots.txt your extension can't find it. 
Can you add an extra field to override the path to robots.txt ?

**Comment by adampmoss** [comment]
Hi Hans, I see what you're doing but I don't quite understand what you're asking regarding the field?

**Comment by hans2103** [comment]
System > Configuration > Creare SEO > robots.txt is trying to get magento-root/robots.txt
This file doesn't exist since they are stored in magento-root/robots/<hostname>/robots.txt
Therefor I can't use your tool
Adding the field where I can specify the location of the file would help me to use your tool again.

**Comment by adampmoss** [comment]
Ok, I see. I'll note this down for the next update.

**Comment by adampmoss** [comment]
This is now included in 1.3
