### ISSUE TITLE
blank page Creare SEO Checklist v1.3.1

### ISSUE THREAD

**Issue by hans2103** [Creare/CreareSEO#24]
installing CreareSEO version 1.3.1, clean cache, log out and log in

I am able to see and change the CreareSEO settings.
I get a blank screen when I want to see the CreareSEO Checklist.
![schermafdruk 2015-06-19 14 24 19](https://cloud.githubusercontent.com/assets/639822/8253318/ee15c870-168e-11e5-9065-6c7da35ffde9.png)

**Comment by adampmoss** [comment]
Never seen that one before! Are you seeing any errors in your logs?

**Comment by hans2103** [comment]
After calling the CreaseSEO Checklist page 
$ tail -f ~/example.com/var/log/system.log
2015-06-22T09:17:53+00:00 CRIT (2): Not valid template file:adminhtml/default/default/template/creareseo/check.phtml

**Comment by adampmoss** [comment]
Can you check if the file "adminhtml/default/default/template/creareseo/check.phtml" is there? https://github.com/Creare/CreareSEO/blob/master/app/design/adminhtml/default/default/template/creareseo/check.phtml

**Comment by hans2103** [comment]
I've installed Creare SEO using modman. 
therefor the directory you mention is a symlink. 
Can this be an issue?

**Comment by adampmoss** [comment]
I've not experienced this issue before with modman. The symlinks should be a problem. Does the error go away if the file is physically in the directory?

**Comment by JamesAnelay** [comment]
@hans2103 You need to Allow templates as symlinks.

So System > Configuration >Advanced > Developer > Allow Symlinks - Set this to YES.

//cc @adampmoss

**Comment by adampmoss** [comment]
@JamesAnelay great spot James!

**Comment by hans2103** [comment]
Thank you @JamesAnelay and @adampmoss 
allow symlinks solved the issue. 

Mind that when you activate symlinks there is a warning below:
> Warning! Enabling this feature is not recommended on production environments because it represents a potential security risk.

@avoelkl wrote an excellent answer about a related question on StackExchange
http://magento.stackexchange.com/a/35254/6311

bottom line: use at own risk.

I will reinstall the plugin without modman.

**Comment by JamesAnelay** [comment]
Indeed @hans2103.
If you take a look in the githubmodman readme (https://github.com/colinmollenhour/modman/blob/master/README.md) you'll see it states "NOTE: There is no additional security risk to allowing symlinks, despite the warning which says otherwise..." - Allthough obviously those posts would disagree.

FYI: Modman also has an option to copy files rather than symlink using --copy.

[--copy]           deploy by copying files instead of symlinks

**Comment by hans2103** [comment]
nice addition. Thank you @JamesAnelay
