### ISSUE TITLE
Error with SearchAction

### ISSUE THREAD

**Issue by gputignano** [Creare/CreareSEO#25]
I installe dthe last version of creareseo magento extension and in Structured Data Testing Tool I get 2 errors as you can see in the attached image. The url of the site is http://www.lacompagniadelcavatappi.com.

![rich-snippet](https://cloud.githubusercontent.com/assets/77434/8334643/57675d94-1a99-11e5-8a93-3c824e08a852.png)

**Comment by adampmoss** [comment]
Thanks for this, I'll check it out and update it this week

**Comment by adampmoss** [comment]
I just tried it and am not getting any errors?

**Comment by gputignano** [comment]
I checked the code and it seems ok but I get this error. You can check the page http://www.lacompagniadelcavatappi.com

**Comment by gputignano** [comment]
Now it seems to be ok!

**Comment by adampmoss** [comment]
Strange one. Keep an eye on it!
