### ISSUE TITLE
<meta name="robots" content="NOINDEX" for a second page of a category list

### ISSUE THREAD

**Issue by singalen** [Creare/CreareSEO#26]
The filter arguments detection on category page is very primitive: https://github.com/Creare/CreareSEO/blob/master/app/code/community/Creare/CreareSeoCore/Model/Observer.php#L12 - only by presence of `'?'`, e.g. any parameter.

When I add a `?p=2` parameter (a page number 2), it still should be `INDEX`ed, but I'm getting `NOINDEX`.

This approach I googled up didn't work, apparently the registries are not initialized yet:

                $_category = Mage::registry('current_category');
                if(!empty($_category)) {
                    $_filters = Mage::getSingleton('catalog/layer')->getState()->getFilters();
                } else {
                    $_filters = Mage::getSingleton('catalogsearch/layer')->getState()->getFilters();
                }

Are there any better options than hardcoding `p` parameter?

**Comment by adampmoss** [comment]
Are you saying that you want to exempt the '?p=' from the noindex layout updates, while maintaining the noindex on the filters?

**Comment by singalen** [comment]
Exactly. If the category is indexed, then all of its pages should be.
Any other URL parameter: filer, page size, sort order, session id etc - will only produce duplicate content. But adding only a page number fetches unique products, not present of the first page of a category.

**Comment by adampmoss** [comment]
I think we'd need to grab the keys of the querystring, if there's only 1 and it === 'p' then exit the function. Feel free to have a go and PR if you want. If you don't I'll have a go at it soon.

**Comment by adampmoss** [comment]
Just as a side note, I think preventing robots access to index the various pages is a better idea because if you have a category description, this will be duplicated across the different pages and Google may see this as duplicate content.

**Comment by singalen** [comment]
I missed that, as I'm in no way a SEO specialist. Now I consulted a specialist, and suddenly it's more complex than that:
* All of the category pages should be indexed;
* pages>1 should have a respective meta tag;
* pages>1 should NOT contain the category text;
* links to next/previous pages should have `rel=”next”`/`rel=”prev”` attributes;
* there should be a way to tell Google that p parameter is responsible for paging.
* Ideally, a one-field filter on a category page should be indexed either, and have a unique text for this very category and field. If there is no copywriting manpower for that, then filtered URL should not be indexed.

**Comment by adampmoss** [comment]
1. All category pages are indexed so that's ok.
2. Pages > 1 are not currently indexed and DO contain category text - this last bit is something that could be fixed with an observer
3. rel=next" and "prev" are not included in native Magento or this extension
4. I'll take a look into this and get back to you. This article is an interesting read: https://moz.com/ugc/seo-guide-to-google-webmaster-recommendations-for-pagination
5. Not sure what this last point means?

**Comment by singalen** [comment]
no.5 is described there: http://searchenginewatch.com/sew/how-to/2225544/take-out-duplication-without-a-single-site-change - the "paginates" option of `URL Parameters` in Google Webmaster Tools.

I don't see how a HTML can hint Googlebot that `p` is a pagination parameter, it was just an idle curiosity.

**Comment by adampmoss** [comment]
I'll discuss this with the team and we'll make any necessary updates.

**Comment by adampmoss** [comment]
We have discussed this internally and have decided that the extension deals with pagination in the most appropriate way. Pagination is marked by meta "next" and "prev" rel tags, so Google is able to crawl those pages and index any subsequently found links (products), whilst maintaining that the original version of the category page is the one to be indexed. This deals with duplicate content and also effectively communicates the pagination to Google.

If you really want to you can enable the ?p= tag to be indexable as well by disabling the setting in the extension's config, but you should make sure their pagination settings are correct within webmaster tools. We wouldn't recommend this though. We won't be making any further adjustments to the extension in this area, however feel free to fork and PR if you want to make the modifications yourself.
