### ISSUE TITLE
Product Schema JSON Does not Validate

### ISSUE THREAD

**Issue by notoveryet** [Creare/CreareSEO#28]
Hi, the Product Schema JSON does not validate because single quotes are escaped and they shouldn't be. Therefore,

app/code/community/Creare/CreareSeoCore/Block/Schema/Product.php

return strip_tags(addslashes($string));

should be

return strip_tags(addcslashes($string, '"\\/'));

Hope this helps.

**Comment by adampmoss** [comment]
Well spotted. This has now been added https://github.com/Creare/CreareSEO/commit/81e0edcdcb20cbea12f3626d2698c0f6c49b9831
