### ISSUE TITLE
HTTP/HTTPS Mod in Cmscanonical.php

### ISSUE THREAD

**Issue by BradChism** [Creare/CreareSEO#31]
There was an issue with the site when loading the Canonical and forcing the site to SSL. It would still show HTTP and not HTTPS:// so here is the change in Cmscanonical 

near the bottom. Replace 
return 'http://'.$host.$path;

with the code below, save it and upload the new file back to your server. The site will now change to HTTPS if your site is running under HTTPS, otherwise it will stay HTTP

if (Mage::app()->getStore()->isCurrentlySecure()):
//  HTTPS code goes here 
return 'https://'.$host.$path;
  else : 
 // HTTP code goes here
 return 'http://'.$host.$path;
endif; 

        Little hack but it works. Hopefully you guys can patch the main files for the next version.

Thanks,
Brad

**Comment by adampmoss** [comment]
This has been added to a recent push.
