### ISSUE TITLE
Enabling "Make "alt" tags mandatory on product gallery images?" made "Images" product admin tab blank

### ISSUE THREAD

**Issue by singalen** [Creare/CreareSEO#32]
![screenshot from 2015-07-28 01 56 55](https://cloud.githubusercontent.com/assets/151199/8919928/39b042dc-34cc-11e5-8af3-5a8a65132e2c.png)

Disabling it returns images tab controls back.

I can provide extra details about my configuration.

**Comment by adampmoss** [comment]
Thanks for reporting this, are you getting any JS errors in your console?

**Comment by singalen** [comment]
No. Only one 404 for a CSS: 
`http://tahta.com.ua/skin/adminhtml/base/default/themeoptions.css Failed to load resource: the server responded with a status of 404 (Not Found)`, and that happens before the tab loads.

**Comment by adampmoss** [comment]
Strange, I've not seen this happen anywhere else. Do you have any other admin area extensions enabled?

**Comment by albertobraschi** [comment]
in magento 1.9.3 have the same issue.
after disabling the alt mandatory upload and showing image.
