### ISSUE TITLE
microdata / rich snippets - grouped products, price shows as 0

### ISSUE THREAD

**Issue by iphigenie** [Creare/CreareSEO#34]
The generated JSON does not seem to have a case for grouped products in the use case "hide simple products and show them together on grouped products page" 

Instead of creating an offers loop over the associated products (eg: size/colour price), it just shows an offer entry with price 0

  "offers": {
        "@type": "Offer",
    "price": "0.00",
        "availability": "InStock",
    "priceCurrency": "GBP"
  }}

what I would expect is and "offers" "Offer" "itemOffered" loop
 
Now that's fine, I already customised my templates directly for this use case so my page contains correct code, but because of the creare JSON is at the top mine gets  ignored.

Short term fixes?

- Option to disable "offers" separately from products.
- Option to disable "offers" for grouped products.

Long term fix

- override for "grouped" which adds

**Comment by iphigenie** [comment]
my solution has been to create an extended version of template\creareseo\product\schema.html in my local design

I'm pretty sure it does not cover all the possible "grouped product" scenarios when it comes to availability and prices etc. but it does generate so far

"offers": [  
	{
	    	"@type": "Offer",
	    	"availability": "InStock",
	    	"itemOffered": {
	    			"sku": "3332176"	,
	    			"name": "my product name"	
	    	                 },
	    	"priceCurrency": "GBP",
	    	"price": "12.7"
	}  , 		
       {
	    	 "@type": "Offer",
	    	  "availability": "InStock",
	    	  "itemOffered": {
	    			"sku": "3312018"	,
	    			"name": "my product name"	
	    	  },
	    	"priceCurrency": "GBP",
	    	"price": "12.23"
	}     	
]

how to add the option values I haven't yet looked at

**Comment by adampmoss** [comment]
Thanks for sharing this. Could you share the code with me if you'd prefer not to PR?

**Comment by iphigenie** [comment]
I just don't think it is general enough - and I'm mostly winging it in Magento and in git ;) - to pass as a PR

But I can try :)

**Comment by iphigenie** [comment]
Hi @adampmoss 

I think I have done it right - see https://github.com/Creare/CreareSEO/pull/36

As I said, I was fixing it for my own site (pleased that I can just put the 1 template in my design tree and it works!) so there might be some scenarios it doesn't work for
