### ISSUE TITLE
Can't save settings

### ISSUE THREAD

**Issue by yasinkocak** [Creare/CreareSEO#37]
I use the latest version of CreareSEO and Magento 1.9.2.1

I have changes on my settings of CreareSEO i can not save. I push the save button but no effect.

If i go to another settings of Magento the button works?

**Comment by adampmoss** [comment]
Hello, are there any JS or PHP log errors being reported?

**Comment by yasinkocak** [comment]
I have found the issue.

There was a field required and the tab was collapsed. Nothing to see when u push the button even not a notification. When the tab is collapsed u can not see there is required field Address Locality at Organization Schema.
