### ISSUE TITLE
supee-6788

### ISSUE THREAD

**Issue by blopa** [Creare/CreareSEO#41]
Hi!

The new Magento update breaks CreareSEO. I'm not sure what should be changed for the module to work properly again. Is there a schedule to update the module to work with the new Magento version?

Thanks

**Comment by adampmoss** [comment]
Yeah, we'll update the module this week. What specifically have you noticed when you say it's not working?

**Comment by blopa** [comment]
Hey Adam. Thanks for the reply. I wasn't able to acess the module admin page. This happened with many other modules I use, so for production sake I restore my backup, so I'm not sure exactly what was wrong with it besides the admin page acess.

Best.

**Comment by sasoriza** [comment]
Did you disable "Admin routing compatibility mode for extensions" in the security settings? Could be the reason you can't access some of your extensions.
In either case, this extension shouldn't be affected by that as it uses the default admin url. I can access the configuration without any problem by the way (1.9.2.2, "Admin routing compatibility mode" enabled as I am still waiting for a couple of extensions to get updated)

**Comment by adampmoss** [comment]
@blopa - @sasoriza is correct, the admin has been routed correctly and I'm not able to replicate the problem. Could you check your admin routing compatibility settings?

**Comment by blopa** [comment]
It turns out I forgot to clear cache. Shame on me. Sorry about that, folks. Great work with the extension. Thanks

**Comment by adampmoss** [comment]
No worries, thanks for looking out for us!
