### ISSUE TITLE
Fatal Error When Mage_Review Disabled

### ISSUE THREAD

**Issue by sprankhub** [Creare/CreareSEO#48]
When the module Mage_Review is disabled, the extension produces a fatal error [here](https://github.com/Creare/CreareSEO/blob/master/app/code/community/Creare/CreareSeoCore/Block/Schema/Product.php#L25). It would be great if it was checked whether Mage_Review is available.

**Comment by infabo** [comment]
#61

**Comment by sprankhub** [comment]
Thanks @infabo!
