### ISSUE TITLE
Magento BE Access to "CreareSEO Checklist"

### ISSUE THREAD

**Issue by knospe-** [Creare/CreareSEO#55]
Hello,

we have installed your CreareSEO Extension. We had no problem with the installation and configuration of the extension.

We have more than one team working on our webshop and each team has it's own permission role for the Magento Backend. 
It has come to our attention that only the users with user role "Administrators" can access the "CreareSEO Checklist" area in Magento Backend. Even if we create a new user role and grant it permission to all Backend areas, the users of this new role still cannot access "CreareSEO Checklist". The message that they get is "Access denied.". Having different access permissions for the backend is very important to us, because we do not wish that every backend user has for example access to sales.

Is it possible to grant permission to "CreareSEO Checklist" to a user role different than "Administration"?

**Comment by zigojacko** [comment]
Does it have a <acl> section in the extension config?

You can add this yourself quite simple, see [here](http://stackoverflow.com/a/3202150).

**Comment by knospe-** [comment]
@zigojacko Thank you for your quick reply. Everything works as it should if I login as Admin user to the Magento Backend. If I login with a different user with a user role different than "Administrators", I cannot access the "CreareSEO Checklist".
Is it possible to set the extension configuration file, so that access to the specific module Backend areas are granted only to a specific user group?

**Comment by zigojacko** [comment]
I am only guessing here as I have not looked at the code (I just for some reason am subscribed to issues on this project, heh) but I think you might require the `_isAllowed()` method in the admin controller of the extension in order for other roles to be able to access in the backend.

You can read more on implementing this [here](http://magento.stackexchange.com/a/79911/798) and [here](http://stackoverflow.com/a/12745145/898933).

Hope that helps?

**Comment by knospe-** [comment]
That was it! Thank you so much for your help :)

**Comment by zigojacko** [comment]
You're welcome :)
